version: '3.8'
services:
  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=willianbrun
      - DB_PASSWORD=password
      - DB_NAME=microservicos
    depends_on:
      - postgres
    networks:
      - api-network
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: masterkey
      POSTGRES_DB: api
    ports:
      - "5000:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - api-network
networks:
  api-network:
    driver: bridge
volumes:
  postgres-data: